import React, {useState, useEffect} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Container } from 'react-bootstrap';
import Header from '../components/Header'
import ProductLists from '../components/ProductLists'

export default function Home() {

  const [cart, setCart] = useState([]);
  const [itemCount, setItemCount] = useState(0);

  useEffect(()=>{
    const saved = localStorage.getItem("cart");
    if(cart.length > 0){
        localStorage.setItem('cart', JSON.stringify(cart));
        setItemCount(cart.length);
    }
    // else{
    //   if(saved && JSON.parse(saved).length > 0){
    //     const myCart = JSON.parse(saved);
    //     localStorage.setItem('cart', JSON.stringify(myCart));
    //     setItemCount(myCart.length);
    //     //setCart(myCart);
    //   }else{
    //     const demoCart = [];
    //     localStorage.setItem('cart', JSON.stringify(demoCart));
    //   }
    // }

  },[cart])

  let flag = 0;

  const addToCart = (id, event) => {
    
      const cartData = {
          productId: id,
          quantity: 1
      }
      
      const saved = localStorage.getItem("cart");
      const myCart = JSON.parse(saved);

      

      if(myCart && myCart.length > 0){
        for(let el of myCart){
          if(el.productId == id){
              el.quantity = el.quantity + 1;
              flag++
              break;
          }
        }
      }

      if(flag == 0){
        if(myCart && myCart.length > 0){
          setCart([...myCart , cartData]);
        }else{
          setCart([...cart , cartData]);
        }
          
      }else{
          setCart(myCart);
          flag = 0;
      }

      event.preventDefault();
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header itemCount={itemCount}/>

      <Container>
        <ProductLists addToCart={addToCart}/>
      </Container>

    </div>
  )
}
